config/routes.rb
Rails.application.routes.draw do
  # root to: 'details#index'
  root to: 'posts#index'
  resources :details
  resources :posts
  # root to: 'welcome#home'
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :todos
    end
  end
  resources :todos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/detail.rb
class Detail < ApplicationRecord
  has_one_attached :image
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :destroy, :edit, :update]

  def index
  end

  def new
    @detail = Detail.new
  end

  def create
    puts"==========#{detail_params.inspect}============="
    @detail = Detail.new(detail_params)
    # @detail.image.attach(params[:image])
    if @detail.save
      respond_to do |format|
        format.js
        format.html { redirect_to @detail, notice: "save successfully 111" }
      end
    else
      render 'new'     # render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @detail.update(detail_params)
      respond_to do |format|
        format.js
        format.html { redirect_to @detail }
      end
    else
      render 'edit'
    end
  end

  def destroy
    @detail.destroy
    @abc = 'abc'
    respond_to do |format|
      format.js
      format.html {redirect_to details_path, notice: 'Post was successfully destroyed.'}
    end

  end

  private

  def set_detail
    @detail = Detail.find(params[:id])
  end
  def detail_params
    params.require(:detail).permit(:name, :email, :image)
  end
end


# redirect_to controller: 'thing', action: 'edit', id: 3, something: 'else'
# redirect_to :back, flash: {new_solution_errors: solution.errors}
# redirect_to new_user_path(:id => 1, :contact_id => 3, :name => 'suleman')
#

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_detail.html.erb
<tr>
  <td><%=detail.name %></td>
  <td><%=detail.email %></td>
  <td><%= link_to 'delete', detail, method: :delete, data: { confirm: 'Are you sure?'}, remote: true, class: 'delete' %></td>
  <td><%= link_to 'Edit', edit_detail_path(detail), remote:true, class: 'edit' %></td>

</tr>

app/views/details/_form.html.erb
<%= form_with model: @detail, local: false do |form|%>
  <div class="field">
    <%= form.label :'Name' %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :'Email' %>
    <%= form.email_field :email %>
  </div>
  <div class="field">
    <%= form.label :'Image' %>
    <%= form.file_field :image %>
  </div>
  <!--  <div class="actions">-->
  <%= form.submit 'save' %>
  <!--  </div>-->
<% end %>

app/views/details/create.js.erb
$('.details-table').append('<%= j render 'detail', detail: @detail %>');
$('#new-detail form').remove();
$('#new-detail a').show();

app/views/details/destroy.js.erb
$('.delete').bind('ajax:success', function(){
    $(this).closest('tr').fadeOut();
})

app/views/details/edit.html.erb
<%= render 'form' %>

app/views/details/edit.js.erb
$('#new-detail a').hide().parent().append('<%= j render 'form' %>').fadeIn(5000);

app/views/details/index.html.erb
<%#= javascript_pack_tag 'index' %>
<br>
<br>

<table style="margin-left: 10%" class='details-table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>email</th>
      <th>terms and conditions</th>
      <th>edit</th>
    </tr>
  </thead>
  <tbody>
    <% Detail.all.each do |detail| %>
      <%= render 'detail', detail: detail%>
    <% end %>
  </tbody>
</table>

<br>
<br>
<div id='new-detail'>
  <%= link_to 'add new detail', new_detail_path , id: 'new-detail-link'%>
</div>

<script>
    $(document).ready(function(){
        say_hello('ABer')
    });
</script>

app/views/details/new.html.erb
<%= render 'form' %>
<button type="button" class="btn btn-success">Primary</button>
<%= link_to 'Back', details_path %>

app/views/details/new.js.erb
$('#new-detail a').hide().parent().append('<%= j render 'form' %>').fadeIn(5000);

app/views/details/show.html.erb
<p><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @detail.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @detail.email %>
</p>
<%= link_to 'Back', details_path %>
<%#= link_to 'Edit', edit_detail_path(@detail) %>

app/views/details/update.js.erb
//$('.delete').bind('ajax:success', function(){
//    $(this).closest('tr').html('<%= j render 'detail', detail: @detail %>');
//    $("tr td#edit").parent().replaceWith().html('<%= j render 'detail', detail: @detail %>');
//})
$('tr td a.edit').bind('ajax:success', function(){
    $(this).parent().closest('tr').html('<%= j render 'detail', detail: @detail %>')
})

//$('tr td a.edit').parent().parent().html('<%= j render 'detail', detail: @detail %>')

//$('.details-table').append('<%= j render 'detail', detail: @detail %>');
$('#new-detail form').remove();
$('#new-detail a').show();